apiVersion: batch/v1
kind: CronJob

metadata:
  name: hello-world

spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid

  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command: ["/bin/sh", "-c", "echo Hello from Kubernetes"]

          restartPolicy: OnFailure