jobs:
  - name: run-script-on-ec2-with-ssm
    plan:
      - task: run-remote-script
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: amazon/aws-cli

          params:
            AWS_ACCESS_KEY_ID: ((ec2.aws_access_id))
            AWS_SECRET_ACCESS_KEY: ((ec2.aws_access_key_secret))
            AWS_DEFAULT_REGION: ap-south-1
            AWS_EC2_ID: ((ec2.instance_id))
            AWS_PAGER: ""

          run:
            path: sh
            args:
              - -exc
              - |
                COMMAND_ID=$(aws ssm send-command \
                  --instance-ids "${AWS_EC2_ID}" \
                  --document-name "AWS-RunShellScript" \
                  --parameters 'commands=["bash /home/ubuntu/ssm_script.sh"]' \
                  --query "Command.CommandId" \
                  --output text)

                echo "Dispatched SSM command: ${COMMAND_ID}"

                while true; do
                  STATUS=$(aws ssm get-command-invocation \
                    --command-id "${COMMAND_ID}" \
                    --instance-id "${AWS_EC2_ID}" \
                    --query "Status" \
                    --output text)

                  echo "Current status: ${STATUS}"

                  case "${STATUS}" in
                    Success)
                      echo "=== Remote script succeeded ==="
                      aws ssm get-command-invocation \
                        --command-id "${COMMAND_ID}" \
                        --instance-id "${AWS_EC2_ID}" \
                        --query "StandardOutputContent" \
                        --output text
                      exit 0
                      ;;
                    Failed|Cancelled|TimedOut|Cancelling)
                      echo "=== Remote script failed with status: ${STATUS} ==="
                      aws ssm get-command-invocation \
                        --command-id "${COMMAND_ID}" \
                        --instance-id "${AWS_EC2_ID}" \
                        --query "StandardErrorContent" \
                        --output text
                      exit 1
                      ;;
                    *)
                      sleep 5
                      ;;
                  esac
                done
