resources:
  - name: repo
    type: git
    source:
      uri: ((github.github_url))
      branch: main
      username: ((github.github_username))
      password: ((github.github_token))

  - name: my-docker-image
    type: registry-image
    source:
      repository: test-with-concourse
      tag: latest
      aws_access_key_id: ((ecr.aws_access_key_id))
      aws_secret_access_key: ((ecr.aws_secret_access_key))
      aws_region: ((ecr.aws_region))

jobs:
  - name: push-to-ecr
    plan:
      - get: repo

      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: repo
          outputs:
            - name: image
          params:
            CONTEXT: repo/04_concourse/05_dokcer_image
          run:
            path: build

      - put: my-docker-image
        params:
          image: image/image.tar
        get_params:
          skip_download: true
        attempts: 3
        timeout: 20m
