jobs:
  - name: hello-word
    plan:
      - task: hello-world-task
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: busybox
              tag: latest
          run:
            path: echo
            args: ["hello", "world"]
