resource_types:
  - name: helm3
    type: registry-image
    source:
      repository: ghcr.io/typositoire/concourse-helm3-resource
      tag: v1.30.0

resources:
  - name: repo
    type: git
    source:
      uri: ((github.github_url))
      branch: main
      username: ((github.github_username))
      password: ((github.github_token))

  - name: myapp-helm
    type: helm3
    source:
      cluster_url: ((eks.cluster_url))
      cluster_ca: ((eks.cluster_ca))
      token: ((eks.token))
      aws_eks_cluster_name: archietech-dev
      aws_region: ((eks.aws_region))
      aws_access_key_id: ((eks.aws_access_key_id))
      aws_secret_access_key: ((eks.aws_secret_access_key))
      namespace: default

jobs:
  - name: deploy-test
    plan:
      - get: repo
        trigger: true
      - put: myapp-helm
        params:
          chart: repo/05_eks/chart/eks
          namespace: default
          release: my-app
          values: repo/05_eks/chart/eks/values.yaml
          override_values:
            - key: image.tag
              value: latest
            - key: image.name
              value: test-with-concourse
            - key: image.pullPolicy
              value: Always
          wait: 300
          atomic: true
